spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jrdstart
    username: postgres
    password: postgres
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
